import "./globals.css";
import "antd/dist/reset.css";
import Navbar from "@/components/Navbar/page";
import ClientLayout from "./ClientLayout";
import { ConfigProvider } from "antd";
import { Prompt } from "next/font/google";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next.JS App",
  description: "Generated by create next app",
};

const prompt = Prompt({
  subsets: ["thai", "latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-prompt",
  display: "swap", // ✅ แนะนำ
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={prompt.variable}>
      <body>
        <ConfigProvider
          theme={{
            token: {
              fontFamily: "var(--font-prompt), Arial, sans-serif",
            },
          }}
        >
          <Navbar />
          <main>
            <ClientLayout>{children}</ClientLayout>
          </main>
        </ConfigProvider>
      </body>
    </html>
  );
}
