import "./globals.css";
import "antd/dist/reset.css";
import Navbar from "@/components/Navbar/page";
import ClientLayout from "./ClientLayout";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next.JS App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body>
        <div>
          <Navbar />
          <main>
            <ClientLayout>{children}</ClientLayout>
          </main>
        </div>
      </body>
    </html>
  );
}
